project:
  type: website
  output-dir: docs
  resources: 
    - images/
    - data/

website:
  title: ""
  navbar:
    background: "#FFFFFF"
    foreground: "#BD3039"
    logo: "images/thesabrhood2clean.png"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: leaderboards.qmd
        text: Leaderboards
      - href: about.qmd
        text: About
      
format:
  html:
    css: styles.css